"""add AI Intelligence Layer tables

Revision ID: 607f99bdd171
Revises: 65031599e6d7
Create Date: 2026-07-15 13:49:30.720972

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# Revision identifiers, used by Alembic.
revision: str = '607f99bdd171'
down_revision: Union[str, None] = '65031599e6d7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('prompt_templates',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('active_version', sa.Integer(), nullable=False),
    sa.Column('ab_testing_enabled', sa.Boolean(), nullable=False),
    sa.Column('ab_split_ratio', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_templates_name'), 'prompt_templates', ['name'], unique=True)
    op.create_table('prompt_versions',
    sa.Column('template_name', sa.String(length=100), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=False),
    sa.Column('user_prompt', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prompt_versions_template_name'), 'prompt_versions', ['template_name'], unique=False)
    op.create_table('skill_aliases',
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.Column('standard_name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_aliases_alias'), 'skill_aliases', ['alias'], unique=True)
    op.create_table('technology_aliases',
    sa.Column('alias', sa.String(length=255), nullable=False),
    sa.Column('standard_name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technology_aliases_alias'), 'technology_aliases', ['alias'], unique=True)
    op.create_table('capability_scores',
    sa.Column('candidate_profile_id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('confidence_score', sa.Float(), nullable=False),
    sa.Column('experience_score', sa.Float(), nullable=False),
    sa.Column('depth_score', sa.Float(), nullable=False),
    sa.Column('breadth_score', sa.Float(), nullable=False),
    sa.Column('proficiency', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', 'EXPERT', name='proficiency_level'), nullable=False),
    sa.Column('explanation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_capability_scores_candidate_profile_id'), 'capability_scores', ['candidate_profile_id'], unique=False)
    op.create_table('chat_conversations',
    sa.Column('candidate_profile_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_conversations_candidate_profile_id'), 'chat_conversations', ['candidate_profile_id'], unique=False)
    op.create_table('evaluation_histories',
    sa.Column('candidate_profile_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluation_histories_candidate_profile_id'), 'evaluation_histories', ['candidate_profile_id'], unique=False)
    op.create_table('evidences',
    sa.Column('candidate_profile_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Enum('RESUME', 'GITHUB', 'LEETCODE', 'CODEFORCES', 'PROJECT', 'COMMIT', name='evidence_source'), nullable=False),
    sa.Column('weight', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Integer(), nullable=False),
    sa.Column('evidence_text', sa.Text(), nullable=False),
    sa.Column('verification_state', sa.String(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evidences_candidate_profile_id'), 'evidences', ['candidate_profile_id'], unique=False)
    op.create_index(op.f('ix_evidences_skill_id'), 'evidences', ['skill_id'], unique=False)
    op.create_table('job_matches',
    sa.Column('candidate_profile_id', sa.UUID(), nullable=False),
    sa.Column('job_title', sa.String(length=255), nullable=False),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('match_data', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_job_matches_candidate_profile_id'), 'job_matches', ['candidate_profile_id'], unique=False)
    op.create_table('platform_syncs',
    sa.Column('candidate_profile_id', sa.UUID(), nullable=False),
    sa.Column('platform', sa.Enum('GITHUB', 'LEETCODE', 'CODEFORCES', name='platform_type', inherit_schema=True), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('sync_status', postgresql.ENUM('PENDING', 'QUEUED', 'RUNNING', 'SUCCESS', 'FAILED', 'RETRY', 'CANCELLED', name='job_status', create_type=False), nullable=False),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('normalized_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('platform_version', sa.String(length=50), nullable=True),
    sa.Column('api_version', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('last_synced_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_syncs_candidate_profile_id'), 'platform_syncs', ['candidate_profile_id'], unique=False)
    op.create_index(op.f('ix_platform_syncs_platform'), 'platform_syncs', ['platform'], unique=False)
    op.create_index(op.f('ix_platform_syncs_sync_status'), 'platform_syncs', ['sync_status'], unique=False)
    op.create_index(op.f('ix_platform_syncs_username'), 'platform_syncs', ['username'], unique=False)
    op.create_table('readiness_reports',
    sa.Column('candidate_profile_id', sa.UUID(), nullable=False),
    sa.Column('backend_score', sa.Float(), nullable=False),
    sa.Column('frontend_score', sa.Float(), nullable=False),
    sa.Column('fullstack_score', sa.Float(), nullable=False),
    sa.Column('ai_score', sa.Float(), nullable=False),
    sa.Column('data_score', sa.Float(), nullable=False),
    sa.Column('devops_score', sa.Float(), nullable=False),
    sa.Column('cloud_score', sa.Float(), nullable=False),
    sa.Column('cybersecurity_score', sa.Float(), nullable=False),
    sa.Column('embedded_score', sa.Float(), nullable=False),
    sa.Column('explanation', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_readiness_reports_candidate_profile_id'), 'readiness_reports', ['candidate_profile_id'], unique=False)
    op.create_table('skill_graph_nodes',
    sa.Column('candidate_profile_id', sa.UUID(), nullable=False),
    sa.Column('node_type', sa.Enum('SKILL', 'PROJECT', 'PLATFORM', 'EVIDENCE', name='graph_node_type'), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_graph_nodes_candidate_profile_id'), 'skill_graph_nodes', ['candidate_profile_id'], unique=False)
    op.create_table('chat_messages',
    sa.Column('conversation_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['conversation_id'], ['chat_conversations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_messages_conversation_id'), 'chat_messages', ['conversation_id'], unique=False)
    op.create_table('skill_graph_edges',
    sa.Column('candidate_profile_id', sa.UUID(), nullable=False),
    sa.Column('source_node_id', sa.UUID(), nullable=False),
    sa.Column('target_node_id', sa.UUID(), nullable=False),
    sa.Column('relationship_type', sa.Enum('KNOWS', 'USES', 'IMPLEMENTS', 'PROVES', 'CLAIMS', name='graph_relationship_type'), nullable=False),
    sa.Column('properties', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['candidate_profile_id'], ['candidate_profiles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_node_id'], ['skill_graph_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_node_id'], ['skill_graph_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skill_graph_edges_candidate_profile_id'), 'skill_graph_edges', ['candidate_profile_id'], unique=False)
    op.create_index(op.f('ix_skill_graph_edges_source_node_id'), 'skill_graph_edges', ['source_node_id'], unique=False)
    op.create_index(op.f('ix_skill_graph_edges_target_node_id'), 'skill_graph_edges', ['target_node_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_skill_graph_edges_target_node_id'), table_name='skill_graph_edges')
    op.drop_index(op.f('ix_skill_graph_edges_source_node_id'), table_name='skill_graph_edges')
    op.drop_index(op.f('ix_skill_graph_edges_candidate_profile_id'), table_name='skill_graph_edges')
    op.drop_table('skill_graph_edges')
    op.drop_index(op.f('ix_chat_messages_conversation_id'), table_name='chat_messages')
    op.drop_table('chat_messages')
    op.drop_index(op.f('ix_skill_graph_nodes_candidate_profile_id'), table_name='skill_graph_nodes')
    op.drop_table('skill_graph_nodes')
    op.drop_index(op.f('ix_readiness_reports_candidate_profile_id'), table_name='readiness_reports')
    op.drop_table('readiness_reports')
    op.drop_index(op.f('ix_platform_syncs_username'), table_name='platform_syncs')
    op.drop_index(op.f('ix_platform_syncs_sync_status'), table_name='platform_syncs')
    op.drop_index(op.f('ix_platform_syncs_platform'), table_name='platform_syncs')
    op.drop_index(op.f('ix_platform_syncs_candidate_profile_id'), table_name='platform_syncs')
    op.drop_table('platform_syncs')
    op.drop_index(op.f('ix_job_matches_candidate_profile_id'), table_name='job_matches')
    op.drop_table('job_matches')
    op.drop_index(op.f('ix_evidences_skill_id'), table_name='evidences')
    op.drop_index(op.f('ix_evidences_candidate_profile_id'), table_name='evidences')
    op.drop_table('evidences')
    op.drop_index(op.f('ix_evaluation_histories_candidate_profile_id'), table_name='evaluation_histories')
    op.drop_table('evaluation_histories')
    op.drop_index(op.f('ix_chat_conversations_candidate_profile_id'), table_name='chat_conversations')
    op.drop_table('chat_conversations')
    op.drop_index(op.f('ix_capability_scores_candidate_profile_id'), table_name='capability_scores')
    op.drop_table('capability_scores')
    op.drop_index(op.f('ix_technology_aliases_alias'), table_name='technology_aliases')
    op.drop_table('technology_aliases')
    op.drop_index(op.f('ix_skill_aliases_alias'), table_name='skill_aliases')
    op.drop_table('skill_aliases')
    op.drop_index(op.f('ix_prompt_versions_template_name'), table_name='prompt_versions')
    op.drop_table('prompt_versions')
    op.drop_index(op.f('ix_prompt_templates_name'), table_name='prompt_templates')
    op.drop_table('prompt_templates')
    # ### end Alembic commands ###
