"""Analysis database model.

Stores the generated evaluation report and tracking for a candidate's analysis.
"""

import uuid
from typing import TYPE_CHECKING

from sqlalchemy import Enum, ForeignKey, String
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.database.base import Base
from app.database.models.enums import AnalysisState

if TYPE_CHECKING:
    from app.database.models.candidate_profile import CandidateProfile


class Analysis(Base):
    """The generated AI capability analysis report for a candidate."""

    __tablename__ = "analyses"

    candidate_profile_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("candidate_profiles.id", ondelete="CASCADE"),
        index=True,
        nullable=False,
        doc="The candidate profile this analysis is for.",
    )
    state: Mapped[AnalysisState] = mapped_column(
        Enum(AnalysisState, name="analysis_state", native_enum=True),
        nullable=False,
        default=AnalysisState.PENDING,
        doc="Current state of the analysis process.",
    )
    overall_score: Mapped[float | None] = mapped_column(
        nullable=True,
        doc="Aggregate capability score (0-100).",
    )
    report_data: Mapped[dict | None] = mapped_column(
        JSONB,
        nullable=True,
        doc="Structured JSON report generated by AI.",
    )

    # Relationships
    candidate_profile: Mapped["CandidateProfile"] = relationship(
        "CandidateProfile",
        back_populates="analyses",
    )
    history: Mapped[list["AnalysisHistory"]] = relationship(
        "AnalysisHistory",
        back_populates="analysis",
        cascade="all, delete-orphan",
        passive_deletes=True,
        order_by="AnalysisHistory.created_at",
    )


class AnalysisHistory(Base):
    """Tracking history of state changes for an Analysis."""

    __tablename__ = "analysis_history"

    analysis_id: Mapped[uuid.UUID] = mapped_column(
        ForeignKey("analyses.id", ondelete="CASCADE"),
        index=True,
        nullable=False,
        doc="The parent analysis.",
    )
    state: Mapped[AnalysisState] = mapped_column(
        Enum(AnalysisState, name="analysis_state", native_enum=True),
        nullable=False,
        doc="The state the analysis entered.",
    )
    message: Mapped[str | None] = mapped_column(
        String(255),
        nullable=True,
        doc="Optional context or error message for this state transition.",
    )

    # Relationships
    analysis: Mapped["Analysis"] = relationship(
        "Analysis",
        back_populates="history",
    )
